### PR TITLE
refactored

### PR DESCRIPTION
**Pull request by misterfourtytwo**
seen ur project on reddit

made logic cleaner and less error-prone
ui is somewhat flexible and scales lil bit
added sounds in web and android, app now also works on web and linux, should also work on other desktop systems, though haven't checked
forked before you started using your package, imo it's easier for u to edit merge so it will work with it

checked on android, web and linux
hosted on [pages](https://misterfourtytwo.github.io/Shots/#/)

sounds and colors and styles still need some changes though

### CODE REVIEW

**Comment by ninest** [comment]
Thank you so much for taking the time and effort to go through the project and make changes. I haven't gone through everything, but here are some initial comments.
- As of now, I don't have plans for web support. I've only been focusing on iOS and Android at the moment. I saw the example you hosted in GH pages and it seemed good, so I may reconsider.
- Same for desktop. Currently no plans.
- Thanks for informing me about `SizedBox`. I forgot it can be used that way!
- In [this commit](https://github.com/ninest/Shots/pull/8/commits/50795cfd4f83ddb7868a658cc085b8e59e4010d4), you added `const`. Is this not unnecessary?
- About audio, did you test it on an Android device with the latest version of `audioplayers`? It didn't work for me. (There was an issue about this in the audioplayers repository)
- I don't like the new sounds you added and preferred the "popping" sounds I previously had. I plan to add sounds for the cards shuffling too. The sounds [here](https://misterfourtytwo.github.io/Shots/#/) don't fit with the light-hearted nature of the game
- The card behavior has been changed quite a bit under the hood, so I'll ignore those changes for now
- In this [commit](https://github.com/ninest/Shots/pull/8/commits/3a159257d9265fd264a9155453c882f25086097c), why did you use `.map() ... .toList()`? Won't a `for` loop work fine?
- Combing the timer and game provider makes sense

Additionally, what do you mean by "less error-prone"?

Thanks for the PR

Added later:
- I see you changed "Re shuffle" to "Restart". This is not exactly what I'm going for. I want to have a shuffle button just so users can redo a deck without having to restart a game. The timer and no. of cards swiped through will not reset
- Did you change the accent color from Indigo to Green?
- What do you mean by this comment:
    ```
    // TODO adjust constants so they wont try to pluck ur eyes out
    ```
- Why did you add a bottom navigation bar to the Scaffold extension?
- What's the db folder for? Can you point me out the to documentation? Thanks

**Comment by misterfourtytwo** [comment]
const is preset uncahangable value, while getter is a function call, which introduces overhead.
audio works on my phone
i just added random shuffle noise from web
map is usual method for mapping iterables, for loop might have worked, but for cards to update properly they have to get unique keys for them, which is why i use indexOf, if i just used index from for loop framework will just reuse swiped away topcard again and introduce bugs with update
i thought reshuffle button meant for restart, not just for the onscreen deck reset
when i debugged on my monitor colors were really eye gouging, so i changed them a bit. also, blue ones was too dark in comparison to other cards.
so that scaffolding will be written in the same uniform way
db is folder generated by hive when run on my desktop, shoud've removed it, sorry

**Comment by ninest** [comment]
> audio works on my phone

Thanks for testing!

> when i debugged on my monitor colors were really eye gouging, so i changed them a bit. also, blue ones was too dark in comparison to other cards.

Thanks for informing me, I'll look into it

One more thing, you were doing something involving scaling. What exactly were you doing? Trying to make the card sizes responsive to screen sizes?


> map is usual method for mapping iterables, for loop might have worked, but for cards to update properly they have to get unique keys for them, which is why i use indexOf, if i just used index from for loop framework will just reuse swiped away topcard again and introduce bugs with update

Is this the change you were referring to when you said "made logic cleaner and less error-prone"

**Comment by misterfourtytwo** [comment]
yeah, before, when card container was too big, it was moving only in one axis, or movement weren't visible at all.
also added layout rebuilds in main screen menu, before when switched to landscape some of the widgets were rendered off-screen

**Comment by ninest** [comment]
I'm sorry, but I don't think I'll merge this pull request. There are too many changes. The new sound you added is nice, but there's too much I'll have to roll back. Additionally, I haven't planned web support yet as there are still some issues on Android and iOS I am yet to fix. 

Next time please make smaller PRs after discussing by creating issues. Thank you so much for your efforts!

**Comment by misterfourtytwo** [comment]
well, i did it mostly for myself.
i think i might implement other things later, like creating custom packs, feel free to watch my fork.

**Comment by ninest** [comment]
Sure, thanks for understanding!

**Pull request closed without merging**
